### ISSUE TITLE
replace上传目录不可写，nicen_make-localize-image本地化插件无法生效！

### ISSUE THREAD

**Issue by ausboyue** [friend-nicen/nicen-localize-image#15]
<img width="429" alt="image" src="https://github.com/user-attachments/assets/155b58b7-4ef4-4d01-9b7f-4b16d8de1949" />

**Comment by friend-nicen** [comment]
wp-contents/uploads/replace ，这个设置目录权限可写

**Comment by ausboyue** [comment]
> wp-contents/uploads/replace ，这个设置目录权限可写

已经设置了哦

<img width="699" alt="image" src="https://github.com/user-attachments/assets/0e89f1f3-7e6a-46ff-b3aa-93cb1af44d62" />

**Comment by ausboyue** [comment]
wp版本：6.6.2

**Comment by friend-nicen** [comment]
加微信good7341
