### ISSUE TITLE
replace上传目录不存在|不可写，nicen_make-localize-image本地化插件无法生效！

### ISSUE THREAD

**Issue by ausboyue** [friend-nicen/nicen-localize-image#16]
报了这两个错：
- 错1：
<img width="429" alt="image" src="https://github.com/user-attachments/assets/155b58b7-4ef4-4d01-9b7f-4b16d8de1949" />

- 错2：
<img width="431" alt="image" src="https://github.com/user-attachments/assets/e8f179bd-b56d-42a2-8a96-eff0d08d0606" />

**Comment by friend-nicen** [comment]
wp-contents/uploads/replace ，这个设置目录权限可写

**Comment by friend-nicen** [comment]
- [ ]
