### ISSUE TITLE
插件权限问题

### ISSUE THREAD

**Issue by enjoy-it** [friend-nicen/nicen-localize-image#2]
config配置
PLUGIN_nicen_make 项  capablity 不应该是edit_themes

配置了禁止编辑文件， 直接导致插件不可用.
define('DISALLOW_FILE_EDIT', true);
define('DISALLOW_FILE_MODS', true);

没有权限管理， 配置manage_options 应该就可以

**Comment by friend-nicen** [comment]
收到🤦‍♂️🤦‍♂️🤦‍♂️
