### ISSUE TITLE
随便测试了一下 出错了

### ISSUE THREAD

**Issue by qian9008** [friend-nicen/nicen-localize-image#5]
2022-10-21 14:42:41，本地化失败，https:// /2022/09/14/x2y2xu.png图片链接无法访问！
可能是防盗链防采集？

**Comment by friend-nicen** [comment]
https:// /2022/09/14/x2y2xu.png图片链接无法访问！
请问中间没有域名吗？
下载的时候会自动模拟Referer，防盗链理论是无效的。

**Comment by qian9008** [comment]
> 请问中间没有域名吗？

有啊 https://z.run/i/2022/09/14/x3jre7.png
或许是 ua 问题？

**Comment by friend-nicen** [comment]
@qian9008 

 https://z.run/i/2022/09/14/x3jre7.png

我用自己的wordpress试了一下，本地化成功了。

🤦‍♂️🤦‍♂️🤦‍♂️，你这个本地化失败可能跟你服务器有关系

**Comment by qian9008** [comment]
好吧，我的🐔被墙了，无法访问国内资源。

**Comment by friend-nicen** [comment]
🤣🤣🤣🤣🤣，生活还得继续
