### ISSUE TITLE
压缩超过5MB以上图片时报错

### ISSUE THREAD

**Issue by xwyrz** [friend-nicen/nicen-localize-image#6]
![Z@P`J8LI3BD}FBV (W@S8O4](https://user-images.githubusercontent.com/61658739/201501809-23755563-abb3-41e8-84ad-3e32f0d19e0e.png)
另外这个error_long  是不是应该是 error_log

**Comment by friend-nicen** [comment]
🤣🤣🤣，我也觉得应该是error_log，但是这是人家接口输出的。

用的压缩接口是[resmush.sh](https://resmush.it/)，照这个报错来看，人家限制了最大5M。

**Comment by xwyrz** [comment]
> 🤣🤣🤣，我也觉得应该是error_log，但是这是人家接口输出的。
> 
> 
> 
> 用的压缩接口是[resmush.sh](https://resmush.it/)，照这个报错来看，人家限制了最大5M。

算了，影响不大。本地压缩一遍在上传了，好在就几张图片

**Comment by friend-nicen** [comment]
> 稳妥
