### ISSUE TITLE
提交BUG

### ISSUE THREAD

**Issue by joeyreg** [friend-nicen/nicen-localize-image#9]
每次第一次本地化都不能全部本地化，要运行第二次才行

**Comment by friend-nicen** [comment]
麻烦把遇到问题的文章的html代码发出来，我去试试

**Comment by joeyreg** [comment]
https://blog.csdn.net/meigang2012/article/details/124841231
csdn都有这个问题

**Comment by friend-nicen** [comment]
上一次保存文章后，本地化图片成功25张，失败0张！自动添加alt属性26个！可在插件设置页面查看日志！原封不动的复制过去的，全部本地化成功🤦‍♂️

**Comment by joeyreg** [comment]
我是在文章编辑器里点击外部图片替换，然后需要点两次才能全部本地化，看你说的是不是全部保存后去插件页面一次性本地化所有文章更好？

**Comment by friend-nicen** [comment]
编辑器的那个本地化插件，确实有这情况，估计是处理速度太快了，有些处理过的又被覆盖了。
下个版本我修一修。

**Comment by qijianchuan** [comment]
希望添加图片自动命名功能,如根据日期,文章名等

**Comment by friend-nicen** [comment]
等待发版
